services:
  redis:
    image: redis:latest
    container_name: url-shortener-redis
    command: bash -c "apt update && apt install -y redis-tools && redis-server"
    ports:
      - "6379:6379"
    restart: on-failure
    networks:
      - url-shortener-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"  # Jaeger UI
      - "14250:14250"  # Jaeger gRPC endpoint
    networks:
      - url-shortener-network

networks:
  url-shortener-network:
    name: url-shortener-network  # Ensures no prefix is added
    driver: bridge