services:
#  app:
#    container_name: url-shortener-app
#    build:
#      context: ../..
#      dockerfile: src/infra/Dockerfile
#    restart: unless-stopped
#    environment:
#      - SPRING_REDIS_HOST=url-shortener-redis  # Explicitly set redis host and port
#      - SPRING_REDIS_PORT=6379
#      - AWS_ACCESS_KEY_ID=AKIA4A2EUGSLBBDL6BFT
#      - AWS_SECRET_ACCESS_KEY=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
#      - AWS_REGION=us-east-1
#      - NEW_RELIC_LICENSE_KEY=795b4d6e00f3f102d68044aa1ccad632FFFFNRAL
#    ports:
#      - "8080:8080"
#    depends_on:
#      redis:
#        condition: service_healthy
#    networks:
#      - url-shortener-network

  redis:
    image: redis:latest
    container_name: url-shortener-redis
    command: bash -c "apt update && apt install -y redis-tools && redis-server"
    ports:
      - "6379:6379"
    restart: on-failure
    networks:
      - url-shortener-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  url-shortener-network:
    name: url-shortener-network  # Ensures no prefix is added
    driver: bridge