services:
  redis:
    image: redis:latest
    container_name: redis-local
    command: bash -c "apt update && apt install -y redis-tools && redis-server"
    ports:
      - "6379:6379"
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge