services:
  app:
    container_name: url-shortener-app
    build: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - url-shortener-network

  redis:
    image: redis:latest
    container_name: url-shortener-redis
    command: bash -c "apt update && apt install -y redis-tools && redis-server"
    ports:
      - "6379:6379"
    networks:
      - url-shortener-network

networks:
  url-shortener-network:
    driver: bridge