name: CI/CD - Build and Push Docker Image

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "CI - Build and Test" ]
    types:
      - completed
  push:
    branches:
      - main

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Ensures CI passed
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      # Set BUILD_TAG based on branch name and run number
      - name: Set BUILD_TAG
        run: |
          echo BUILD_TAG=$(echo "${{ github.head_ref || github.ref_name }}" | sed "s,/,_,g")-${{ github.run_number }} >> $GITHUB_ENV

      # Print BUILD_TAG for verification
      - name: Print BUILD_TAG defined
        run: |
          echo "Branch     ---> ${{ github.head_ref || github.ref_name }}"
          echo "Run number ---> ${{ github.run_number }}"
          echo "Tag        ---> ${{ env.BUILD_TAG }}"

      # Step to build the JAR file
      - name: Build JAR file
        run: mvn clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build Docker image with BUILD_TAG
      - name: Build Docker image
        run: docker build -t reginaldolribeiro/url-shortener:${{ env.BUILD_TAG }} -f src/infra/Dockerfile .

      # Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push reginaldolribeiro/url-shortener:${{ env.BUILD_TAG }}
