name: CI - Build and Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Build
        run: mvn clean compile

      - name: Run Unit Tests
        run: mvn verify

      - name: Run Integration Tests, Generate JaCoCo Report, and Enforce Coverage Threshold
        run: mvn verify jacoco:report -DskipUnitTests -Djacoco.coverage.minimum=0.8

      - name: Upload JaCoCo Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco

      - name: Upload Integration Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-integration-report
          path: target/site/jacoco-integration